### ISSUE TITLE
How to import obl to Unity?

### ISSUE THREAD

**Issue by Simmywang** [Vampyr7878/LegoGeometryViewer#1]
Thank you very much for the software.It is really a great job.I have got the .obl file and I wonder how to import the file to Unity as a asset.I tried to change the suffix to obj but it didn`t work.

**Comment by Vampyr7878** [comment]
The project contains folder called OBLImporter. You just put this into your Unity project Assets folder. It is a script for unity to imort those obl files, they are slightly different from obj in order to support brick colors and materials. If you have importer in your project then you just put obl files in your project or reimoport them and it should give you 3d meshes.

**Comment by Simmywang** [comment]
I have successfully imported the .obl.Thank you very much!
There is still a problem with the texture.When I import the ldd to LegoGeometryViewer,the colors are the same displayed in SharpGl form.Will you please teach me what to do,thank you.

**Comment by Vampyr7878** [comment]
The color in SharpGl form doesn't represent actual color it is something i just chose randomly. When you put the actual obl file in Unity project it should have exact same colors as it has in ldd without the prints

**Comment by Simmywang** [comment]
Okay,I have got materials in Unity,thank you very much.It is very kind of you.May I ask where you are from?

**Comment by Vampyr7878** [comment]
Why would you like to know that?

**Comment by Simmywang** [comment]
I want to make friends with you for great help.I am from China.
